{
 "title": "Monitoring",
 "time": { "from": "2024-09-10T04:01:01.815Z", "to": "2024-09-10T04:11:01.815Z" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Usage Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( crm_active_connections / crm_total_users ) * 100",
     "legendFormat": "CRM"
    },
    {
     "expr": "( gstock_active_connections / gstock_total_users ) * 100",
     "legendFormat": "G-Stock"
    }
   ]
  },
  {
   "title": "Active Connexions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crm_active_connections", "legendFormat": "CRM" },
    { "expr": "gstock_active_connections", "legendFormat": "G-Stock" }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "crm_total_users", "legendFormat": "CRM" },
    { "expr": "gstock_total_users", "legendFormat": "G-Stock" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crm_error_rate_percentage", "legendFormat": "CRM" },
    { "expr": "gstock_error_rate_percentage", "legendFormat": "G-Stock" }
   ]
  },
  {
   "title": "Alerts History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ALERTS{instance=~\"$instance\", alertname=~\"$alertname\", alertstate=~\"$alertstate\"}",
     "legendFormat": "{{alertname}} {{instance}} {{alertstate}} {{datacenter}}"
    },
    { "expr": "1", "legendFormat": "help_series_x_axes_in_center" }
   ]
  },
  {
   "title": "GStock User Activities",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{__name__=~\"gstock_user_action_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRM User Activities",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "{__name__=~\"crm_user_action_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}